# Generated by Django 5.2 on 2025-04-08 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='word',
            old_name='english_word',
            new_name='en',
        ),
        migrations.RemoveField(
            model_name='word',
            name='translated_word',
        ),
        migrations.RemoveField(
            model_name='word',
            name='user_id',
        ),
        migrations.AddField(
            model_name='word',
            name='is_admin_word',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='word',
            name='ru',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.JSONField(default=list)),
                ('text', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructions', to=settings.AUTH_USER_MODEL)),
                ('words', models.ManyToManyField(to='trainer.word')),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='trainer.room'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_learned', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to='trainer.word')),
            ],
        ),
    ]
