# Generated by Django 5.2 on 2025-04-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_sentencetemplate_delete_construction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentencetemplate',
            name='translate',
            field=models.CharField(default='Посмотри на', max_length=255),
            preserve_default=False,
        ),
    ]
