# Generated by Django 5.2 on 2025-04-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0009_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='playback_speed',
            field=models.FloatField(default=1),
        ),
    ]
