# Generated by Django 5.2 on 2025-05-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0010_usersettings_playback_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='lesson_repeat_count',
            field=models.SmallIntegerField(default=1),
        ),
    ]
