# Generated by Django 5.2 on 2025-05-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0012_chapter_room_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentencesTranslate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_en', models.CharField(max_length=255)),
                ('sentence_ru', models.CharField(max_length=255)),
            ],
        ),
    ]
