# Generated by Django 5.2 on 2025-06-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0016_wordrecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='use_own_recordings_if_available',
            field=models.BooleanField(default=False),
        ),
    ]
