# Generated by Django 5.2 on 2025-06-01 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0017_usersettings_use_own_recordings_if_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='preferred_other_user',
            field=models.ForeignKey(blank=True, help_text="The user whose voice recordings are preferred, if voice_preference_type is 'other_user'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='voice_preference_type',
            field=models.CharField(choices=[('tts', 'Default TTS'), ('own', 'Own Recordings'), ('other_user', 'Other User Recording')], default='tts', max_length=10),
        ),
    ]
